// Auto-generated by scripts/fetch-google-reviews.mjs
// To populate with real reviews, run:
//   GOOGLE_PLACES_API_KEY=your_key node scripts/fetch-google-reviews.mjs
//
// Get your Place IDs from:
//   https://developers.google.com/maps/documentation/places/web-service/place-id-finder

export interface GoogleReview {
  author: string;
  rating: number;
  text: string;
  date: string;
  profilePhoto: string;
  location: string;
}

export interface LocationReviewMeta {
  id: string;
  label: string;
  placeId: string;
  rating: number;
  reviewCount: number;
}

// Replace these with real data by running the fetch script
export const locationReviewMeta: LocationReviewMeta[] = [
  {
    id: "chandigarh",
    label: "Chandigarh HQ",
    placeId: "REPLACE_WITH_CHANDIGARH_PLACE_ID",
    rating: 4.9,
    reviewCount: 250,
  },
  {
    id: "edmonton",
    label: "Edmonton Office",
    placeId: "REPLACE_WITH_EDMONTON_PLACE_ID",
    rating: 5.0,
    reviewCount: 100,
  },
];

export const googleReviews: GoogleReview[] = [];

export const combinedRating = 4.9;
export const totalReviewCount = 350;
